[targets.test]
command = "npm test"
depends_on = ["//self:deps"]

[targets.test-ci]
command = "npm test"
depends_on = ["//self:deps"]

[targets.deps]
command = "npm ci"

[targets.check-generated-example]
command = "npm test"
depends_on = ["//self:deps"]

[targets.lint]
command = "npm audit --audit-level=high"

[targets.build]
command = "npm pack --dry-run"
