// @generated by quint-refinements from model.qnt. Do not edit.
// Regenerate with `quint-refinements compile`.
#![allow(dead_code)]

use quint_refinements::{
    AsyncPrimitiveDriver, ConformanceArtifact, FixtureTable, NormalizedRuntimeEvidence,
    OwnershipTable, PrimitiveDriver, ResolvedAction, RuntimeValue, collect_ownership_records,
    quint_ownership, refine_scenario,
};

const TRACES: &str = include_str!("traces.json");

quint_ownership! {
    const ABORT = {
        primitive: "two_phase_commit.abort",
        refines: ["abort"],
        aliases: [],
        observations: ["path:state.flushed", "path:state.status", "path:state.wal"],
        retrieve: ["name:state"],
    };
}

quint_ownership! {
    const BEGIN = {
        primitive: "two_phase_commit.begin",
        refines: ["begin"],
        aliases: [],
        observations: ["path:state.flushed", "path:state.status", "path:state.wal"],
        retrieve: ["name:state"],
    };
}

quint_ownership! {
    const COMMIT = {
        primitive: "two_phase_commit.commit",
        refines: ["prepare", "flushWal", "commitPrepared"],
        aliases: [],
        observations: ["path:state.flushed", "path:state.status", "path:state.wal"],
        retrieve: ["name:state"],
    };
}

/// Which implementation command owns each Quint action.
pub const OWNERSHIP: OwnershipTable = OwnershipTable {
    owner: "two_phase_commit-generated-refinement",
    descriptors: &[ABORT, BEGIN, COMMIT],
};

/// Everything the generated obligations may read from a snapshot.
pub const RETRIEVE: &[&str] = &[
    "name:Aborted",
    "name:Committed",
    "name:state",
    "name:statuses",
    "operator:List",
    "operator:Rec",
    "operator:append",
    "operator:assign",
    "operator:contains",
    "operator:eq",
    "operator:field",
    "operator:or",
    "operator:with",
    "path:state.flushed",
    "path:state.status",
    "path:state.wal",
];

/// Domain implementation connected to the generated Quint scenarios.
pub trait Implementation: Sized {
    /// Snapshot type exposed to the refinement evaluator.
    type Evidence: NormalizedRuntimeEvidence + Clone;

    /// Construct the implementation from a scenario's generated initial state.
    fn from_initial_state(initial_state: &RuntimeValue) -> Result<Self, String>;

    /// Return the current observable implementation state.
    fn snapshot(&self) -> Self::Evidence;

    /// Bind model fixtures to production values when the model declares fixtures.
    fn fixtures() -> FixtureTable {
        FixtureTable::new("two_phase_commit")
    }

    /// Execute Quint action `abort` with its generated arguments.
    fn abort(&mut self, arguments: &[RuntimeValue]) -> Result<(), String>;

    /// Execute Quint action `begin` with its generated arguments.
    fn begin(&mut self, arguments: &[RuntimeValue]) -> Result<(), String>;

    /// Execute Quint actions `prepare`, `flushWal`, `commitPrepared` as one command.
    ///
    /// Return one snapshot taken after each action, in that order.
    fn commit(&mut self, actions: &[ResolvedAction]) -> Result<Vec<Self::Evidence>, String>;
}

/// Result of refining one generated Quint run.
pub struct ScenarioResult<I> {
    /// Fully qualified generated scenario name.
    pub scenario: String,
    /// Number of evaluated guard and next-state obligations.
    pub evaluated_obligations: usize,
    /// Implementation state after the scenario completed.
    pub implementation: I,
}

/// Dispatches each owned Quint action sequence to its implementation hook.
pub struct Driver<I> {
    /// The implementation under refinement.
    pub implementation: I,
}

impl<I: Implementation> PrimitiveDriver for Driver<I> {
    type Evidence = I::Evidence;

    fn run_primitive(
        &mut self,
        primitive: &str,
        actions: &[ResolvedAction],
    ) -> Result<Vec<Self::Evidence>, String> {
        match primitive {
            "two_phase_commit.abort" => {
                let [action] = actions else {
                    return Err(format!("abort expects one Quint action; got {actions:?}"));
                };
                if action.name != "abort" {
                    return Err(format!("abort primitive cannot refine {}", action.name));
                }
                self.implementation.abort(&action.arguments)?;
                Ok(vec![self.implementation.snapshot()])
            }
            "two_phase_commit.begin" => {
                let [action] = actions else {
                    return Err(format!("begin expects one Quint action; got {actions:?}"));
                };
                if action.name != "begin" {
                    return Err(format!("begin primitive cannot refine {}", action.name));
                }
                self.implementation.begin(&action.arguments)?;
                Ok(vec![self.implementation.snapshot()])
            }
            "two_phase_commit.commit" => {
                let expected = ["prepare", "flushWal", "commitPrepared"];
                if actions
                    .iter()
                    .map(|action| action.name.as_str())
                    .ne(expected)
                {
                    return Err(format!("commit refines {expected:?}; got {actions:?}"));
                }
                self.implementation.commit(actions)
            }
            other => Err(format!("unknown generated primitive {other}")),
        }
    }
}

impl<I> AsyncPrimitiveDriver for Driver<I>
where
    I: Implementation + Send,
    I::Evidence: Send,
{
    type Evidence = I::Evidence;

    async fn run_primitive(
        &mut self,
        primitive: &str,
        actions: &[ResolvedAction],
    ) -> Result<Vec<Self::Evidence>, String> {
        PrimitiveDriver::run_primitive(self, primitive, actions)
    }
}

/// Parse the generated scenarios this module was compiled with.
pub fn artifact() -> Result<ConformanceArtifact, String> {
    ConformanceArtifact::parse(TRACES).map_err(|error| error.to_string())
}

/// Run every generated conformance scenario against a fresh implementation.
pub fn refine_all<I: Implementation>() -> Result<Vec<ScenarioResult<I>>, String> {
    let artifact = artifact()?;
    let ownership = collect_ownership_records(&[OWNERSHIP]).map_err(|error| error.to_string())?;
    let fixtures = I::fixtures();
    fixtures
        .validate(&artifact)
        .map_err(|error| error.to_string())?;
    let mut results = Vec::new();

    for scenario in &artifact.scenarios {
        let initial_json = scenario
            .initial_state
            .as_ref()
            .ok_or_else(|| format!("{} has no generated initial state", scenario.id()))?;
        let initial_state = RuntimeValue::from_itf_json(initial_json)?;
        let implementation = I::from_initial_state(&initial_state)?;
        let initial_evidence = implementation.snapshot();
        let mut driver = Driver { implementation };
        let evaluated_obligations = refine_scenario(
            scenario,
            initial_evidence,
            &ownership,
            RETRIEVE,
            &fixtures,
            &mut driver,
        )?;
        results.push(ScenarioResult {
            scenario: scenario.id(),
            evaluated_obligations,
            implementation: driver.implementation,
        });
    }

    Ok(results)
}
