// @generated by quint-refinements. Regenerate with the compile command.
use quint_refinements::{
    ConformanceArtifact, FixtureTable, NormalizedRuntimeEvidence, OwnershipTable, PrimitiveDriver,
    ResolvedAction, RuntimeValue, collect_ownership_records, quint_ownership, refine_scenario,
};

const TRACES: &str = include_str!("../quint-refinements.json");

quint_ownership! {
    const WITHDRAW = {
        primitive: "bank.withdraw",
        refines: ["withdraw"],
        aliases: [],
        observations: ["path:state.balance"],
        retrieve: ["name:state"],
    };
}

const OWNERSHIP: OwnershipTable = OwnershipTable {
    owner: "bank-generated-refinement",
    descriptors: &[WITHDRAW],
};

const RETRIEVE: &[&str] = &[
    "name:state",
    "operator:Rec",
    "operator:assign",
    "operator:eq",
    "operator:field",
    "operator:igt",
    "operator:igte",
    "operator:isub",
    "path:state.balance",
];

/// Domain implementation connected to the generated Quint scenarios.
pub trait Implementation: Sized {
    /// Snapshot type exposed to the refinement evaluator.
    type Evidence: NormalizedRuntimeEvidence + Clone;

    /// Construct the implementation from a scenario's generated initial state.
    fn from_initial_state(initial_state: &RuntimeValue) -> Result<Self, String>;

    /// Return the current observable implementation state.
    fn snapshot(&self) -> Self::Evidence;

    /// Bind model fixtures to production values when the model declares fixtures.
    fn fixtures() -> FixtureTable {
        FixtureTable::new("bank")
    }

    /// Execute Quint action `withdraw` with its generated arguments.
    fn withdraw(&mut self, arguments: &[RuntimeValue]) -> Result<(), String>;
}

/// Result of refining one generated Quint run.
pub struct ScenarioResult<I> {
    /// Fully qualified generated scenario name.
    pub scenario: String,
    /// Number of evaluated guard and next-state obligations.
    pub evaluated_obligations: usize,
    /// Implementation state after the scenario completed.
    pub implementation: I,
}

struct Driver<I> {
    implementation: I,
}

impl<I: Implementation> PrimitiveDriver for Driver<I> {
    type Evidence = I::Evidence;

    fn run_primitive(
        &mut self,
        primitive: &str,
        actions: &[ResolvedAction],
    ) -> Result<Vec<Self::Evidence>, String> {
        match primitive {
            "bank.withdraw" => {
                let [action] = actions else {
                    return Err(format!(
                        "withdraw expects one Quint action; got {actions:?}"
                    ));
                };
                if action.name != "withdraw" {
                    return Err(format!("withdraw primitive cannot refine {}", action.name));
                }
                self.implementation.withdraw(&action.arguments)?;
                Ok(vec![self.implementation.snapshot()])
            }
            other => Err(format!("unknown generated primitive {other}")),
        }
    }
}

/// Run every generated conformance scenario against a fresh implementation.
pub fn refine_all<I: Implementation>() -> Result<Vec<ScenarioResult<I>>, String> {
    let artifact = ConformanceArtifact::parse(TRACES).map_err(|error| error.to_string())?;
    let ownership = collect_ownership_records(&[OWNERSHIP]).map_err(|error| error.to_string())?;
    let fixtures = I::fixtures();
    fixtures
        .validate(&artifact)
        .map_err(|error| error.to_string())?;
    let mut results = Vec::new();

    for scenario in &artifact.scenarios {
        let initial_json = scenario
            .initial_state
            .as_ref()
            .ok_or_else(|| format!("{} has no generated initial state", scenario.id()))?;
        let initial_state = RuntimeValue::from_itf_json(initial_json)?;
        let implementation = I::from_initial_state(&initial_state)?;
        let initial_evidence = implementation.snapshot();
        let mut driver = Driver { implementation };
        let evaluated_obligations = refine_scenario(
            scenario,
            initial_evidence,
            &ownership,
            RETRIEVE,
            &fixtures,
            &mut driver,
        )?;
        results.push(ScenarioResult {
            scenario: scenario.id(),
            evaluated_obligations,
            implementation: driver.implementation,
        });
    }

    Ok(results)
}
